---
title: ""
format: docx
bibliography: resources/Phd-bibliography.bib
csl: resources/acta-physiologica.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

P1: Skeletal muscle mass and exercise - age
- How does age affect skeletal muscle mass?
- How does RT affect skeletal muscle mass (generally or for old?)

P2: Age differences might be related to -> ribosomal markers
- Anabolic resistance -> lower MPS in old compared to young
- Lower MPS due to impaired ribosome biogenesis

P3: Ribosomes and exercise
- Exercise can change ribosome biogenesis
- But, a higher training volume might be necessary for the elderly than the young

P4: Finishing up
- Should tie together this: age negatively affects skeletal muscle mass and ribosome biogenesis, but RT positively affects skeletal muscle mass and ribosome biogenesis
- Aims


# Introduction draft 2

Skeletal muscle mass and -strength declines with age, and is best prevented or treated with regular resistance training (RT). The decline in muscle mass and -strength advances upon reaching approximately 50 years of age and accelerates further after reaching 70, and, if left unchecked, has a high probability of leading to sarcopenia [@fragala_resistance_2019; @timmons_molecular_2016]. Muscular weakness and low muscle mass *per se* is further linked to diabetes, disability, cognitive decline, osteoporosis and early all-cause mortality, prevented/treated by either attaining or maintaining a healthy skeletal muscle mass [@fragala_resistance_2019; @li_associations_2018; @scheerman_sarcopenia_2021]. Elderly are expected to gain similar benefits from RT as young, i.e., increased muscle mass, -strength and overall physical performance [@chen_is_2023; @hamarsland_native_2019; @marzuca-nassr_muscle_2024]. To ensure maximal gains from a period of RT, the anabolic stimulus provided from exercising must be sufficient, and ideally combined with nutritional optimisation (especially daily protein addition) [@chen_is_2023; @hamarsland_native_2019; @marzuca-nassr_muscle_2024; @paulussen_anabolic_2021]<!-- check Paulussen and Chaillou -->. Notably, there are considerable inter-individual inter-individual variations in adaptations to RT, especially in the elderly, making prescription of an optimal RT program for different phenotypes difficult [@bamman_cluster_2007; @hammarstrom_benefits_2020-1; @hubal_variability_2005; @stec_effects_2015; @stec_ribosome_2016-1, @timmons_variability_2011]. While the underlying mechanisms of inter-individual variations to RT are not fully elucidated, differential manifestations of aging makes the older population quite more heterogeneous than the young [@hodson_molecular_2019; @timmons_molecular_2016]. 

This heterogeneity in physical function among the elderly is reflected by, perhaps most notably, the different presence of pathophysiological conditions such as insulin resistance, sarcopenia, and anabolic resistance [@fragala_resistance_2019; @hodson_molecular_2019; @timmons_molecular_2016]. Whether anabolic resistance is a contributor to or a consequence of sarcopenia is uncertain, but the lower muscle protein synthesis (MPS) in the elderly following a session of RT or protein ingestion suggests that skeletal muscle in elderly are less responsive to anabolic stimuli than in the young [@atherton_muscle_2012; @timmons_molecular_2016; @wall_aging_2015]. Baseline levels of MPS does not differ with age, however, the activity in proteins that influence MPS (e.g., mTOR) are elevated in fasted muscle from the elderly compared to young [@hodson_molecular_2019; @timmons_molecular_2016; @markofski_effect_2015]. This discrepancy in mTOR activity is proposed to represent either a compensation to increased relative muscle loading due to decreased muscle mass with age, or dysregulation of the mTOR complex [@timmons_molecular_2016]. Further, likely as a consequence of altered mTOR regulation, ribosomal gene transcription and subsequently ribosome biogenesis is reduced in elderly [@chaillou_does_2023; @hodson_molecular_2019; @timmons_molecular_2016]<!--Sjekk disse -->, postulated to explain the anabolic resistance in the elderly in a recent study by Chaillou & Montiel-Rojas [@chaillou_does_2023].

Ribosomes are the protein factories of the cell, and the increase in ribosomal content (translational capacity) following onset of RT is believed to provide support for skeletal muscle fibre hypertrophy [@figueiredo_regulation_2019; @figueiredo_revisiting_2019]. Regardless of age, individuals who respond to RT exhibit an accumulation in markers of ribosome biogenesis (e.g., total RNA and/or rRNA), compared to those who do not experience benefits of RT [@hammarstrom_benefits_2020; @stec_ribosome_2016; @stec_effects_2015]. The findings from Hammarstrom et al. [@hammarstrom_benefits_2020] and Stec et al. [@stec_ribosome_2016] along with research from Figueiredo et al. [@figueiredo_regulation_2019; @figueiredo_revisiting_2019] suggests that ribosome biogenesis is indeed a prerequisite for RT-induced adaptations, increasing the translational capacity of the exercised skeletal muscle cells, yielding higher baseline MPS and thus hypertrophy over time. Though occuring across the age-span, the variation in ribosome biogenesis is probosed to be larger or more impactful among the elderly, substantiated by recent findings of impaired ribosome biogenesis in aging skeletal muscle [@chaillou_does_2023; @hodson_molecular_2019]. If the ribosome biogenesis response following RT varies due to differential responsiveness between elderly, it may be sufficient to simply increase the RT volume to enhance the anabolic stimulus and thus ensure ribosome biogenesis and ultimately skeletal muscle growth. Benefits of increasing training volume was observed recently, where elderly defined as "nonresponders" experienced improved whole muscle tissue hypertrophy by exercising with a higher training volume [@lixandrao_higher_2024]. 

Therefore, this study aims to compare muscle mass accretion and ribosome biogenesis in healthy young and old individuals exercising with a low and a higher training volume for 12 weeks, to provide further knowledge on the effects of RT on age-related declines in muscle mass and -strength, and a possible startegy to counteract anabolic resistance. In addition, it aims to provide insight into the effects of resistance training on a range of health-related variables, including glucose tolerance, health-related biomarkers in fasted-state blood, markers of the metabolic syndrome and cardiovascular health, all of which are associated with age-related issues (Comment: will be adjusted to what we have time for) [@bonomini_metabolic_2015; @north_intersection_2012], and for which we have scarce or conflicting knowledge [@westcott_resistance_2012; @strasser_resistance_2010]. Together, the results of this study will provide novel insight on how to optimise RT for different phenotypes, and whether or not RT is also an effective tool to improve less explored health variables in healthy young and elderly.



# References



